import type { GlobalConfig } from 'payload'
import { adminOnly, anyone } from '../access'

export const CoursesSettings: GlobalConfig = {
  slug: 'courses-settings',
  label: 'Courses Page',
  admin: {
    group: 'Pages',
  },
  access: {
    read: anyone,
    update: adminOnly,
  },
  fields: [
    { name: 'title', type: 'text', localized: true, defaultValue: 'Courses' },
    { name: 'subtitle', type: 'textarea', localized: true, defaultValue: 'Learn with DPI Robotics Club | official and unofficial members welcome.' },
    { name: 'sortLatest', type: 'text', localized: true, defaultValue: 'Latest' },
    { name: 'sortPopular', type: 'text', localized: true, defaultValue: 'Most popular' },
    { name: 'empty', type: 'textarea', localized: true, defaultValue: 'No published courses yet. Please check back soon.' },
    { name: 'lessons', type: 'text', localized: true, defaultValue: 'lessons' },
    { name: 'enrolled', type: 'text', localized: true, defaultValue: 'enrolled' },
    { name: 'hoursShort', type: 'text', localized: true, defaultValue: 'h' },
    { name: 'progress', type: 'text', localized: true, defaultValue: 'Your progress:' },
    { name: 'joinToEnroll', type: 'text', localized: true, defaultValue: 'Join to enroll' },
    { name: 'startLearning', type: 'text', localized: true, defaultValue: 'Start learning' },
    { name: 'enrollNow', type: 'text', localized: true, defaultValue: 'Enroll now' },
    { name: 'free', type: 'text', localized: true, defaultValue: 'Free' },
    { name: 'levelUnknown', type: 'text', localized: true, defaultValue: 'All levels' },
    { name: 'categoryFallback', type: 'text', localized: true, defaultValue: 'Course' },
    {
      name: 'detail',
      type: 'group',
      label: 'Course Detail Page',
      fields: [
        { name: 'whatsappEnroll', type: 'text', localized: true, defaultValue: 'Enroll via WhatsApp' },
        { name: 'contactMissing', type: 'text', localized: true, defaultValue: 'Enrollment contact not configured' },
        { name: 'students', type: 'text', localized: true, defaultValue: 'students' },
        { name: 'hours', type: 'text', localized: true, defaultValue: 'hours' },
        { name: 'selfPaced', type: 'text', localized: true, defaultValue: 'Self-paced' },
        { name: 'lessonsCount', type: 'text', localized: true, defaultValue: 'lessons' },
        { name: 'certificateBlurb', type: 'text', localized: true, defaultValue: 'Certificate when you finish' },
        { name: 'tabsOverview', type: 'text', localized: true, defaultValue: 'Overview' },
        { name: 'tabsCurriculum', type: 'text', localized: true, defaultValue: 'Curriculum' },
        { name: 'tabsInstructor', type: 'text', localized: true, defaultValue: 'Instructor' },
        { name: 'noDescription', type: 'textarea', localized: true, defaultValue: 'No detailed description for this course.' },
        { name: 'preview', type: 'text', localized: true, defaultValue: 'Preview' },
        { name: 'whatYouLearn', type: 'text', localized: true, defaultValue: 'What you will learn' },
        { name: 'memberBoth', type: 'text', localized: true, defaultValue: 'Official & unofficial' },
        { name: 'memberOfficial', type: 'text', localized: true, defaultValue: 'Official members' },
        { name: 'memberUnofficial', type: 'text', localized: true, defaultValue: 'Unofficial members' },
        { name: 'progressLabel', type: 'text', localized: true, defaultValue: 'Your progress' },
        { name: 'priceHintGuest', type: 'text', localized: true, defaultValue: 'Unofficial from {u} · Official from {o}' },
        { name: 'percentComplete', type: 'text', localized: true, defaultValue: '{p}% complete' },
        { name: 'noteGuest', type: 'textarea', localized: true, defaultValue: 'Create an account, then contact us on WhatsApp to pay and get enrolled.' },
        { name: 'notePay', type: 'textarea', localized: true, defaultValue: 'After you pay, our team will activate your enrollment in the admin panel.' },
        { name: 'noteEnrolled', type: 'textarea', localized: true, defaultValue: 'Jump to the Curriculum tab to continue where you left off.' },
        { name: 'includesTitle', type: 'text', localized: true, defaultValue: 'This course includes' },
        { name: 'include1', type: 'text', localized: true, defaultValue: 'Structured modules (video & documents)' },
        { name: 'include2', type: 'text', localized: true, defaultValue: 'Progress tracking' },
        { name: 'include3', type: 'text', localized: true, defaultValue: 'Certificate at 100% (if enabled)' },
        { name: 'allCourses', type: 'text', localized: true, defaultValue: 'All courses' },
        { name: 'verifyCert', type: 'text', localized: true, defaultValue: 'Verify a certificate' },
        { name: 'instructorRole', type: 'text', localized: true, defaultValue: 'Course instructor' },
      ],
    },
  ],
}
