import type { GlobalConfig } from 'payload'
import { adminOnly, anyone } from '../access'

export const EventsSettings: GlobalConfig = {
  slug: 'events-settings',
  label: 'Events Page',
  admin: {
    group: 'Pages',
  },
  access: {
    read: anyone,
    update: adminOnly,
  },
  fields: [
    { name: 'title', type: 'text', localized: true, defaultValue: 'Events' },
    { name: 'subtitle', type: 'textarea', localized: true, defaultValue: 'Upcoming events, workshops, and meetups from DPI Computing Society.' },
    { name: 'empty', type: 'textarea', localized: true, defaultValue: 'No events published yet.' },
    { name: 'emptyDescription', type: 'textarea', localized: true, defaultValue: 'Please check back soon for event updates.' },
    { name: 'backToEvents', type: 'text', localized: true, defaultValue: 'Back to all events' },
    { name: 'upcoming', type: 'text', localized: true, defaultValue: 'Upcoming Events' },
    { name: 'past', type: 'text', localized: true, defaultValue: 'Past Events' },
    { name: 'seatsAvailable', type: 'text', localized: true, defaultValue: 'seats available' },
    { name: 'soldOut', type: 'text', localized: true, defaultValue: 'Sold Out' },
    { name: 'freeEvent', type: 'text', localized: true, defaultValue: 'Free' },
    { name: 'buyTicket', type: 'text', localized: true, defaultValue: 'Buy Ticket' },
    { name: 'loginRequired', type: 'text', localized: true, defaultValue: 'Login to Buy Ticket' },
    { name: 'loginFirst', type: 'textarea', localized: true, defaultValue: 'Please login to purchase a ticket' },
    { name: 'ticketPrice', type: 'text', localized: true, defaultValue: 'Ticket Price' },
    { name: 'eventDetails', type: 'text', localized: true, defaultValue: 'Event Details' },
    { name: 'organizer', type: 'text', localized: true, defaultValue: 'Organizer' },
    { name: 'organizerRole', type: 'text', localized: true, defaultValue: 'Event Organizer' },
    { name: 'quickInfo', type: 'text', localized: true, defaultValue: 'Quick Info' },
    { name: 'startsAt', type: 'text', localized: true, defaultValue: 'Starts at' },
    { name: 'endsAt', type: 'text', localized: true, defaultValue: 'Ends at' },
    { name: 'capacity', type: 'text', localized: true, defaultValue: 'Capacity' },
    { name: 'acceptedPayments', type: 'text', localized: true, defaultValue: 'Accepted Payments' },
    { name: 'buyerName', type: 'text', localized: true, defaultValue: 'Full Name' },
    { name: 'buyerNamePlaceholder', type: 'text', localized: true, defaultValue: 'Enter your full name' },
    { name: 'buyerEmail', type: 'text', localized: true, defaultValue: 'Email Address' },
    { name: 'buyerEmailPlaceholder', type: 'text', localized: true, defaultValue: 'Enter your email' },
    { name: 'buyerPhone', type: 'text', localized: true, defaultValue: 'Phone Number' },
    { name: 'buyerPhonePlaceholder', type: 'text', localized: true, defaultValue: 'Enter your phone number' },
    { name: 'quantity', type: 'text', localized: true, defaultValue: 'Number of Tickets' },
    { name: 'paymentMethod', type: 'text', localized: true, defaultValue: 'Payment Method' },
    { name: 'selectPaymentMethod', type: 'text', localized: true, defaultValue: 'Select payment method' },
    { name: 'transactionId', type: 'text', localized: true, defaultValue: 'Transaction ID' },
    { name: 'transactionIdPlaceholder', type: 'text', localized: true, defaultValue: 'Enter transaction ID' },
    { name: 'transactionIdHelp', type: 'text', localized: true, defaultValue: 'Find this in your mobile banking app after sending money' },
    { name: 'total', type: 'text', localized: true, defaultValue: 'Total' },
    { name: 'handToHandNote', type: 'text', localized: true, defaultValue: 'You will pay in cash when you arrive at the event' },
    { name: 'submitTicket', type: 'text', localized: true, defaultValue: 'Submit Enrollment' },
    { name: 'success', type: 'text', localized: true, defaultValue: 'Enrollment Successful!' },
    { name: 'successMessage', type: 'textarea', localized: true, defaultValue: 'Your ticket has been reserved. You will receive a confirmation email shortly.' },
    { name: 'error', type: 'text', localized: true, defaultValue: 'Error' },
    { name: 'errorMessage', type: 'textarea', localized: true, defaultValue: 'Something went wrong. Please try again.' },
    { name: 'notAvailable', type: 'text', localized: true, defaultValue: 'Not Available' },
    { name: 'featured', type: 'text', localized: true, defaultValue: 'Featured' },
  ],
}
