/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    activities: Activity
    members: Member
    committees: Committee
    'unofficial-members': UnofficialMember
    media: Media
    categories: Category
    posts: Post
    achievements: Achievement
    shop: Shop
    courses: Course
    'course-modules': CourseModule
    'course-progress': CourseProgress
    enrollments: Enrollment
    'lesson-progress': LessonProgress
    'course-reviews': CourseReview
    certificates: Certificate
    'certificate-templates': CertificateTemplate
    forms: Form
    'form-submissions': FormSubmission
    exports: Export
    imports: Import
    search: Search
    'payload-kv': PayloadKv
    'payload-jobs': PayloadJob
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>
    members: MembersSelect<false> | MembersSelect<true>
    committees: CommitteesSelect<false> | CommitteesSelect<true>
    'unofficial-members': UnofficialMembersSelect<false> | UnofficialMembersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    categories: CategoriesSelect<false> | CategoriesSelect<true>
    posts: PostsSelect<false> | PostsSelect<true>
    achievements: AchievementsSelect<false> | AchievementsSelect<true>
    shop: ShopSelect<false> | ShopSelect<true>
    courses: CoursesSelect<false> | CoursesSelect<true>
    'course-modules': CourseModulesSelect<false> | CourseModulesSelect<true>
    'course-progress': CourseProgressSelect<false> | CourseProgressSelect<true>
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>
    'lesson-progress': LessonProgressSelect<false> | LessonProgressSelect<true>
    'course-reviews': CourseReviewsSelect<false> | CourseReviewsSelect<true>
    certificates: CertificatesSelect<false> | CertificatesSelect<true>
    'certificate-templates': CertificateTemplatesSelect<false> | CertificateTemplatesSelect<true>
    forms: FormsSelect<false> | FormsSelect<true>
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>
    exports: ExportsSelect<false> | ExportsSelect<true>
    imports: ImportsSelect<false> | ImportsSelect<true>
    search: SearchSelect<false> | SearchSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: string
  }
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'bn') | ('en' | 'bn')[]
  globals: {
    'header-settings': HeaderSetting
    'footer-settings': FooterSetting
  }
  globalsSelect: {
    'header-settings': HeaderSettingsSelect<false> | HeaderSettingsSelect<true>
    'footer-settings': FooterSettingsSelect<false> | FooterSettingsSelect<true>
  }
  locale: 'en' | 'bn'
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport
      createCollectionImport: TaskCreateCollectionImport
      inline: {
        input: unknown
        output: unknown
      }
    }
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string
  /**
   * Admin: Full access | Instructor: Manage own courses | Editor: Create/edit content | Member: Access courses only
   */
  roles: ('admin' | 'instructor' | 'editor' | 'member' | 'official_member' | 'unofficial_member')[]
  /**
   * Disable to prevent login
   */
  isActive?: boolean | null
  /**
   * Last successful login
   */
  lastLogin?: string | null
  /**
   * Email/OTP verification status
   */
  isVerified?: boolean | null
  /**
   * Official members are linked to Members; others are linked to Unofficial Members.
   */
  memberCategory?: ('official' | 'unofficial') | null
  /**
   * Linked profile for official DPIRC members
   */
  officialMemberProfile?: (string | null) | Member
  /**
   * Linked profile for unofficial members
   */
  unofficialMemberProfile?: (string | null) | UnofficialMember
  otp?: string | null
  otpExpiry?: string | null
  otpAttempts?: number | null
  passwordResetToken?: string | null
  passwordResetExpiry?: string | null
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  /**
   * Authentication method used by this user
   */
  authProvider?: ('email' | 'google') | null
  /**
   * Profile picture from Google
   */
  googlePicture?: string | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string
  /**
   * Unique member identifier for verification
   */
  memberId: string
  /**
   * Public unique username used for profile URL (/profile/[username])
   */
  username: string
  /**
   * Associated user account
   */
  user?: (string | null) | User
  firstName: string
  lastName: string
  fullName?: string | null
  /**
   * Contact email
   */
  email: string
  /**
   * Profile picture
   */
  avatar?: (string | null) | Media
  /**
   * Short biography
   */
  bio?: string | null
  memberType: 'student' | 'instructor' | 'admin'
  /**
   * Technical skills and proficiency levels
   */
  skills?:
    | {
        skill: string
        level?: ('beginner' | 'intermediate' | 'advanced') | null
        id?: string | null
      }[]
    | null
  /**
   * Courses this member is enrolled in
   */
  enrolledCourses?: (string | Enrollment)[] | null
  /**
   * Courses completed by this member
   */
  completedCourses?: (string | Course)[] | null
  /**
   * Certificates earned
   */
  certificates?:
    | {
        course: string | Course
        issuedDate: string
        /**
         * URL to certificate PDF or image
         */
        certificateUrl?: string | null
        id?: string | null
      }[]
    | null
  /**
   * Manual certificate ID for verification
   */
  certificateId?: string | null
  /**
   * Public image URL for the issued certificate
   */
  certificateImageUrl?: string | null
  /**
   * Course linked to this manual certificate
   */
  certificateCourse?: (string | null) | Course
  /**
   * Total points earned from course activities
   */
  totalPoints?: number | null
  /**
   * Member level based on points
   */
  level?: number | null
  /**
   * Whether this member account is active
   */
  isActive?: boolean | null
  /**
   * Committee memberships and roles
   */
  committeeRoles?:
    | {
        committee: string | Committee
        /**
         * Role within the committee (e.g., President, Treasurer)
         */
        role?: string | null
        id?: string | null
      }[]
    | null
  /**
   * Self-serve official signups start as pending; admins approve before the profile appears in /members.
   */
  directoryApprovalStatus: 'pending' | 'approved' | 'rejected'
  /**
   * Admin-entered complaints and warnings
   */
  complaints?:
    | {
        message: string
        status?: ('submitted' | 'in_review' | 'resolved') | null
        createdAt?: string | null
        id?: string | null
      }[]
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees".
 */
export interface Committee {
  id: string
  name: string
  slug: string
  description?: string | null
  badgeColor:
    | 'amber'
    | 'violet'
    | 'sky'
    | 'emerald'
    | 'blue'
    | 'rose'
    | 'orange'
    | 'teal'
    | 'slate'
  priority: number
  isActive?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string
  /**
   * Display title for the media asset
   */
  title?: string | null
  /**
   * Alt text for accessibility and SEO
   */
  alt?: string | null
  /**
   * Detailed description of the media asset
   */
  description?: string | null
  /**
   * Primary usage context
   */
  usage: 'course' | 'post' | 'profile' | 'thumbnail' | 'banner' | 'icon' | 'certificate' | 'general'
  /**
   * Cloud delivery URL from ImageKit
   */
  imageKitUrl?: string | null
  /**
   * ImageKit file identifier
   */
  imageKitFileId?: string | null
  /**
   * Last successful sync to ImageKit
   */
  imageKitSyncedAt?: string | null
  /**
   * Last ImageKit sync error (if any)
   */
  imageKitError?: string | null
  /**
   * File size in bytes
   */
  fileSize?: number | null
  /**
   * Video/audio duration in seconds
   */
  duration?: number | null
  /**
   * Reference count for this asset
   */
  usageCount?: number | null
  /**
   * Last time this asset was linked from content
   */
  lastUsed?: string | null
  /**
   * User who uploaded this asset
   */
  uploadedBy?: (string | null) | User
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  /**
   * Original filename
   */
  filename?: string | null
  /**
   * File MIME type
   */
  mimeType?: string | null
  filesize?: number | null
  /**
   * Image width in pixels
   */
  width?: number | null
  /**
   * Image height in pixels
   */
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    card?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    hero?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}
/**
 * Manage student course enrollments
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: string
  /**
   * The enrolled student
   */
  student: string | User
  /**
   * The course this enrollment belongs to
   */
  course: string | Course
  status: 'active' | 'suspended' | 'completed' | 'revoked'
  /**
   * Member type at time of enrollment
   */
  memberType: 'official' | 'unofficial'
  /**
   * Payment details recorded after WhatsApp confirmation
   */
  payment?: {
    /**
     * Amount paid in BDT
     */
    amount?: number | null
    currency?: ('BDT' | 'USD') | null
    method?: ('bkash' | 'nagad' | 'rocket' | 'bank' | 'cash' | 'free') | null
    /**
     * Transaction ID from payment gateway
     */
    transactionId?: string | null
    paidAt?: string | null
    /**
     * Admin notes about this payment
     */
    notes?: string | null
  }
  /**
   * Overall completion percentage (0–100)
   */
  progress?: number | null
  /**
   * Per-lesson completion records (managed via API)
   */
  lessonProgress?:
    | {
        /**
         * Lesson ID within the course modules array
         */
        lessonId: string
        moduleId: string
        completed?: boolean | null
        completedAt?: string | null
        /**
         * For video lessons: seconds watched
         */
        watchedSeconds?: number | null
        lastAccessedAt?: string | null
        id?: string | null
      }[]
    | null
  /**
   * ID of the last lesson the student accessed (for "resume" button)
   */
  lastLessonAccessed?: string | null
  enrolledAt: string
  /**
   * Set automatically when progress reaches 100%
   */
  completedAt?: string | null
  /**
   * Optional: enrollment expiry date (leave blank for lifetime access)
   */
  expiresAt?: string | null
  /**
   * Issued certificate (auto-linked on completion)
   */
  certificate?: (string | null) | Certificate
  /**
   * Internal admin notes about this enrollment
   */
  adminNotes?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string
  /**
   * Full course title shown to students
   */
  title: string
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string
  /**
   * Shown on course cards (max 300 chars)
   */
  shortDescription: string
  /**
   * Full course description shown on single course page
   */
  description: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  /**
   * Course cover image (recommended: 1280×720px)
   */
  thumbnail?: (string | null) | Media
  /**
   * Optional YouTube/Vimeo embed URL for a free preview
   */
  previewVideo?: string | null
  category:
    | 'robotics-fundamentals'
    | 'programming'
    | 'electronics'
    | 'mechanical'
    | 'ai-ml'
    | 'competition'
    | 'project-management'
  /**
   * Searchable tags for better discoverability
   */
  tags?:
    | {
        tag?: string | null
        id?: string | null
      }[]
    | null
  level: 'beginner' | 'intermediate' | 'advanced'
  language?: ('en' | 'bn' | 'en-bn') | null
  /**
   * Primary instructor for this course
   */
  instructor: string | User
  /**
   * Additional instructors (optional)
   */
  coInstructors?: (string | User)[] | null
  /**
   * Who can enroll in this course
   */
  memberType: 'official' | 'unofficial' | 'both'
  pricing?: {
    /**
     * Price in BDT for official DPI members (0 = free)
     */
    officialMemberPrice?: number | null
    /**
     * Price in BDT for unofficial members (0 = free)
     */
    unofficialMemberPrice?: number | null
    currency?: ('BDT' | 'USD') | null
  }
  /**
   * WhatsApp contact for enrollment
   */
  enrollmentContact: {
    /**
     * WhatsApp number with country code (e.g., +8801XXXXXXXXX)
     */
    whatsappNumber: string
    /**
     * Pre-filled WhatsApp message template. Use {courseName} as placeholder.
     */
    whatsappMessage?: string | null
  }
  duration?: {
    /**
     * Estimated total hours to complete
     */
    totalHours?: number | null
    /**
     * Estimated weeks at recommended pace
     */
    totalWeeks?: number | null
  }
  /**
   * Prerequisites or requirements to join the course
   */
  requirements?:
    | {
        requirement?: string | null
        id?: string | null
      }[]
    | null
  /**
   * What students will be able to do after completing the course
   */
  learningOutcomes?:
    | {
        outcome?: string | null
        id?: string | null
      }[]
    | null
  /**
   * Course curriculum organized into modules
   */
  modules: {
    title: string
    description?: string | null
    /**
     * Display order of this module
     */
    order: number
    lessons: {
      title: string
      type: 'video' | 'document'
      order: number
      /**
       * e.g., "12:34" for video or "10 min read" for documents
       */
      duration?: string | null
      /**
       * Allow non-enrolled users to access this lesson as a free preview
       */
      isFreePreview?: boolean | null
      /**
       * YouTube/Vimeo embed URL or direct video URL
       */
      videoUrl?: string | null
      /**
       * Or upload video directly (use for private hosting)
       */
      videoFile?: (string | null) | Media
      /**
       * Upload PDF, DOCX, or any document
       */
      documentFile?: (string | null) | Media
      /**
       * Or write content directly (shown as rich text)
       */
      documentContent?: {
        root: {
          type: string
          children: {
            type: any
            version: number
            [k: string]: unknown
          }[]
          direction: ('ltr' | 'rtl') | null
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
          indent: number
          version: number
        }
        [k: string]: unknown
      } | null
      /**
       * Short description of this lesson
       */
      description?: string | null
      id?: string | null
    }[]
    id?: string | null
  }[]
  /**
   * Total enrolled students (auto-updated)
   */
  enrollmentCount?: number | null
  /**
   * Average rating out of 5 (auto-calculated)
   */
  averageRating?: number | null
  /**
   * Students who completed 100% (auto-updated)
   */
  completionCount?: number | null
  status: 'draft' | 'review' | 'published' | 'archived'
  publishedAt?: string | null
  /**
   * Pin to featured section on the courses page
   */
  isFeatured?: boolean | null
  /**
   * Certificate configuration for this course
   */
  certificateTemplate?: {
    /**
     * Automatically issue certificate on 100% completion
     */
    issueCertificate?: boolean | null
    /**
     * Title shown on the certificate
     */
    certificateTitle?: string | null
    /**
     * Body text of the certificate (use {studentName}, {courseName}, {completionDate})
     */
    certificateDescription?: string | null
    /**
     * Name of signing authority (e.g., Club President)
     */
    signatoryName?: string | null
    /**
     * Title of signing authority
     */
    signatoryTitle?: string | null
    /**
     * Signature image (PNG with transparent background)
     */
    signatorySignature?: (string | null) | Media
    /**
     * Club logo for the certificate
     */
    clubLogo?: (string | null) | Media
  }
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
}
/**
 * Issued course completion certificates
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: string
  /**
   * Auto-generated unique certificate serial (e.g., DPI-2025-XXXX-XXXX)
   */
  serialNumber: string
  student: string | User
  course: string | Course
  /**
   * The enrollment this certificate was issued for
   */
  enrollment: string | Enrollment
  /**
   * Student data captured at time of issuance (in case user account changes later)
   */
  studentSnapshot: {
    /**
     * Student's full name as it appears on the certificate
     */
    fullName: string
    /**
     * DPI Member ID (if official member) or generated ID
     */
    memberId?: string | null
    memberType?: ('official' | 'unofficial') | null
    email?: string | null
  }
  /**
   * Course data at time of completion
   */
  courseSnapshot: {
    title: string
    instructorName?: string | null
    durationHours?: number | null
  }
  certificateTitle: string
  /**
   * Main body text of the certificate with all placeholders resolved
   */
  certificateBody?: string | null
  signatoryName?: string | null
  signatoryTitle?: string | null
  issuedAt: string
  /**
   * Date the student completed the course (may differ from issuedAt)
   */
  completionDate: string
  /**
   * Uncheck to revoke/invalidate this certificate
   */
  isValid?: boolean | null
  /**
   * Reason for revocation (if isValid is false)
   */
  revokedReason?: string | null
  /**
   * Number of times this certificate has been verified publicly
   */
  verificationCount?: number | null
  lastVerifiedAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unofficial-members".
 */
export interface UnofficialMember {
  id: string
  /**
   * Linked user account
   */
  user?: (string | null) | User
  firstName: string
  lastName: string
  email: string
  /**
   * Profile picture
   */
  avatar?: (string | null) | Media
  /**
   * Short biography
   */
  bio?: string | null
  /**
   * Institution / University / Organization
   */
  institutionName: string
  /**
   * Department, major, or team name
   */
  department?: string | null
  /**
   * Why the user wants to join and any supporting details
   */
  submissionDetails: string
  status: 'pending' | 'approved' | 'rejected'
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string
  /**
   * User who performed the action
   */
  user?: (string | null) | User
  action: 'create' | 'update' | 'delete' | 'publish' | 'login' | 'logout'
  /**
   * Collection affected
   */
  collectionName: string
  /**
   * Document ID affected
   */
  documentId: string
  /**
   * Display title of the document
   */
  documentTitle?: string | null
  /**
   * JSON snapshot of what changed
   */
  changes?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  /**
   * IP address of the request
   */
  ipAddress?: string | null
  /**
   * User agent string
   */
  userAgent?: string | null
  status?: ('success' | 'failed') | null
  /**
   * Additional details or error messages
   */
  details?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string
  name: string
  /**
   * URL-friendly identifier
   */
  slug?: string | null
  /**
   * Brief description of the category
   */
  description?: string | null
  /**
   * What this category is used for
   */
  type: 'course' | 'post' | 'general'
  /**
   * Parent category for hierarchy
   */
  parent?: (string | null) | Category
  /**
   * Category thumbnail image
   */
  thumbnail?: (string | null) | Media
  /**
   * Hex color code for category styling (e.g., #FF5733)
   */
  color?: string | null
  status: 'active' | 'inactive'
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string
  title: string
  /**
   * URL-friendly identifier
   */
  slug?: string | null
  /**
   * Short summary for previews
   */
  excerpt?: string | null
  /**
   * Full post content
   */
  content: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  /**
   * Main image for the post
   */
  featuredImage?: (string | null) | Media
  /**
   * Post author
   */
  author?: (string | null) | Member
  /**
   * Post category
   */
  category?: (string | null) | Category
  /**
   * Tags for better organization
   */
  tags?:
    | {
        tag: string
        id?: string | null
      }[]
    | null
  status: 'draft' | 'published' | 'archived'
  /**
   * Publication date
   */
  publishedAt?: string | null
  /**
   * Estimated reading time in minutes
   */
  readingTime?: number | null
  /**
   * Feature this post on homepage
   */
  featured?: boolean | null
  /**
   * SEO title (leave empty to use post title)
   */
  seoTitle?: string | null
  /**
   * SEO meta description
   */
  seoDescription?: string | null
  /**
   * Number of views
   */
  viewCount?: number | null
  /**
   * Number of likes
   */
  likeCount?: number | null
  /**
   * Search Engine Optimization settings
   */
  seo?: {
    /**
     * SEO title (50-60 characters recommended)
     */
    metaTitle?: string | null
    /**
     * SEO description (150-160 characters recommended)
     */
    metaDescription?: string | null
    /**
     * SEO keywords (comma-separated)
     */
    metaKeywords?: string | null
    /**
     * Canonical URL (leave empty for auto-generation)
     */
    canonicalUrl?: string | null
    /**
     * Prevent search engines from indexing this post
     */
    noIndex?: boolean | null
    /**
     * Open Graph settings for social media sharing
     */
    openGraph?: {
      /**
       * Open Graph title
       */
      ogTitle?: string | null
      /**
       * Open Graph description
       */
      ogDescription?: string | null
      /**
       * Open Graph image (1200x630 recommended)
       */
      ogImage?: (string | null) | Media
    }
    /**
     * Twitter Card settings
     */
    twitterCard?: {
      /**
       * Twitter Card title
       */
      twitterTitle?: string | null
      /**
       * Twitter Card description
       */
      twitterDescription?: string | null
      /**
       * Twitter Card image (1200x600 recommended)
       */
      twitterImage?: (string | null) | Media
    }
  }
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: string
  title: string
  slug: string
  summary: string
  content: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  coverImage?: (string | null) | Media
  gallery?:
    | {
        image: string | Media
        caption?: string | null
        id?: string | null
      }[]
    | null
  achievementDate: string
  venue?: string | null
  organizer?: string | null
  /**
   * Example: Champion, Runner-up, Finalist
   */
  badge?: string | null
  status: 'draft' | 'published' | 'archived'
  featured?: boolean | null
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
}
/**
 * Club merchandise and kits — checkout via WhatsApp
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop".
 */
export interface Shop {
  id: string
  title: string
  slug: string
  /**
   * Shown on product cards
   */
  shortDescription: string
  description: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  featuredImage: string | Media
  /**
   * Extra product photos
   */
  gallery?:
    | {
        image: string | Media
        id?: string | null
      }[]
    | null
  productCategory: 'kits' | 'apparel' | 'electronics' | 'books' | 'other'
  /**
   * Optional stock keeping unit
   */
  sku?: string | null
  memberType: 'official' | 'unofficial' | 'both'
  pricing?: {
    /**
     * Price for official DPI members (0 = free)
     */
    officialMemberPrice?: number | null
    /**
     * Price for unofficial members / public
     */
    unofficialMemberPrice?: number | null
    currency?: ('BDT' | 'USD') | null
  }
  /**
   * WhatsApp for orders (same flow as courses)
   */
  purchaseContact: {
    /**
     * With country code, e.g. +8801XXXXXXXXX
     */
    whatsappNumber: string
    /**
     * Pre-filled message. Use {productName} or {courseName}.
     */
    whatsappMessage?: string | null
  }
  stockStatus: 'in_stock' | 'on_request' | 'sold_out'
  /**
   * Higher appears first within Latest
   */
  sortOrder?: number | null
  status: 'draft' | 'published' | 'archived'
  isFeatured?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * Optional reusable modules linked to a course
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-modules".
 */
export interface CourseModule {
  id: string
  course: string | Course
  title: string
  order: number
  type: 'video' | 'text' | 'quiz'
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  videoUrl?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress".
 */
export interface CourseProgress {
  id: string
  /**
   * The member/student tracking progress
   */
  member: string | Member
  /**
   * The course being tracked
   */
  course: string | Course
  /**
   * List of completed course modules
   */
  completedModules?: (string | CourseModule)[] | null
  /**
   * Auto-calculated: (completedModules / totalModules) * 100
   */
  percentComplete?: number | null
  /**
   * When the student first started the course
   */
  startedAt?: string | null
  /**
   * When the student completed the course (100%)
   */
  completedAt?: string | null
  /**
   * Last time progress was updated
   */
  lastActivityAt?: string | null
  /**
   * Total time spent in minutes
   */
  totalTimeSpent?: number | null
  /**
   * Number of quiz attempts
   */
  quizAttempts?: number | null
  /**
   * Average score across all quizzes (0-100)
   */
  averageQuizScore?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * Per-lesson progress records (auto-managed)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-progress".
 */
export interface LessonProgress {
  id: string
  enrollment: string | Enrollment
  /**
   * Denormalized for faster access queries
   */
  student: string | User
  /**
   * Denormalized for faster access queries
   */
  course: string | Course
  /**
   * ID of the parent module row (Payload array `id`)
   */
  moduleId: string
  /**
   * ID of the lesson row within the module
   */
  lessonId: string
  lessonType?: ('video' | 'document') | null
  completed?: boolean | null
  completedAt?: string | null
  /**
   * For video lessons: seconds watched so far
   */
  watchedSeconds?: number | null
  /**
   * Total video duration in seconds (for % watched calc)
   */
  totalSeconds?: number | null
  lastAccessedAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * Student reviews and ratings for courses
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-reviews".
 */
export interface CourseReview {
  id: string
  student: string | User
  course: string | Course
  /**
   * The enrollment this review is for (ensures only enrolled students can review)
   */
  enrollment?: (string | null) | Enrollment
  /**
   * Rating from 1 to 5 stars
   */
  rating: number
  /**
   * Short review headline
   */
  headline?: string | null
  /**
   * Detailed review text
   */
  body?: string | null
  status: 'pending' | 'approved' | 'rejected'
  /**
   * Reason for rejection (internal)
   */
  adminNote?: string | null
  /**
   * Auto-set to true when student has an active enrollment
   */
  isVerifiedPurchase?: boolean | null
  /**
   * "Found helpful" count from other students
   */
  helpfulCount?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * Legacy / advanced HTML templates for printed certificates
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificate-templates".
 */
export interface CertificateTemplate {
  id: string
  name: string
  type: 'completion' | 'achievement'
  /**
   * HTML template with placeholders such as {{memberName}}, {{courseTitle}}
   */
  templateHtml: string
  /**
   * Optional CSS injected when rendering the template
   */
  cssStyles?: string | null
  backgroundImage?: (string | null) | Media
  signatureImage?: (string | null) | Media
  logoImage?: (string | null) | Media
  status: 'active' | 'inactive'
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string
  title: string
  fields?:
    | (
        | {
            name: string
            label?: string | null
            width?: number | null
            required?: boolean | null
            defaultValue?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'checkbox'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'country'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'email'
          }
        | {
            message?: {
              root: {
                type: string
                children: {
                  type: any
                  version: number
                  [k: string]: unknown
                }[]
                direction: ('ltr' | 'rtl') | null
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
                indent: number
                version: number
              }
              [k: string]: unknown
            } | null
            id?: string | null
            blockName?: string | null
            blockType: 'message'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            defaultValue?: number | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'number'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            defaultValue?: string | null
            placeholder?: string | null
            options?:
              | {
                  label: string
                  value: string
                  id?: string | null
                }[]
              | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'select'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'state'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            defaultValue?: string | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'text'
          }
        | {
            name: string
            label?: string | null
            width?: number | null
            defaultValue?: string | null
            required?: boolean | null
            id?: string | null
            blockName?: string | null
            blockType: 'textarea'
          }
      )[]
    | null
  submitButtonLabel?: string | null
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null
  confirmationMessage?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  redirect?: {
    url: string
  }
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null
        cc?: string | null
        bcc?: string | null
        replyTo?: string | null
        emailFrom?: string | null
        subject: string
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string
            children: {
              type: any
              version: number
              [k: string]: unknown
            }[]
            direction: ('ltr' | 'rtl') | null
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
            indent: number
            version: number
          }
          [k: string]: unknown
        } | null
        id?: string | null
      }[]
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string
  form: string | Form
  submissionData?:
    | {
        field: string
        value: string
        id?: string | null
      }[]
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: string
  name?: string | null
  format: 'csv' | 'json'
  limit?: number | null
  page?: number | null
  sort?: string | null
  sortOrder?: ('asc' | 'desc') | null
  locale?: ('all' | 'en' | 'bn') | null
  drafts?: ('yes' | 'no') | null
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null
  fields?: string[] | null
  collectionSlug: string
  where?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: string
  collectionSlug: string
  importMode?: ('create' | 'update' | 'upsert') | null
  matchField?: string | null
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null
  summary?: {
    imported?: number | null
    updated?: number | null
    total?: number | null
    issues?: number | null
    issueDetails?:
      | {
          [k: string]: unknown
        }
      | unknown[]
      | string
      | number
      | boolean
      | null
  }
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string
  title?: string | null
  priority?: number | null
  doc:
    | {
        relationTo: 'courses'
        value: string | Course
      }
    | {
        relationTo: 'posts'
        value: string | Post
      }
    | {
        relationTo: 'achievements'
        value: string | Achievement
      }
    | {
        relationTo: 'categories'
        value: string | Category
      }
    | {
        relationTo: 'shop'
        value: string | Shop
      }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  taskStatus?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  completedAt?: string | null
  totalTried?: number | null
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string
        completedAt: string
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport'
        taskID: string
        input?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        output?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        state: 'failed' | 'succeeded'
        error?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        id?: string | null
      }[]
    | null
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null
  queue?: string | null
  waitUntil?: string | null
  processing?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string
  document?:
    | ({
        relationTo: 'users'
        value: string | User
      } | null)
    | ({
        relationTo: 'activities'
        value: string | Activity
      } | null)
    | ({
        relationTo: 'members'
        value: string | Member
      } | null)
    | ({
        relationTo: 'committees'
        value: string | Committee
      } | null)
    | ({
        relationTo: 'unofficial-members'
        value: string | UnofficialMember
      } | null)
    | ({
        relationTo: 'media'
        value: string | Media
      } | null)
    | ({
        relationTo: 'categories'
        value: string | Category
      } | null)
    | ({
        relationTo: 'posts'
        value: string | Post
      } | null)
    | ({
        relationTo: 'achievements'
        value: string | Achievement
      } | null)
    | ({
        relationTo: 'shop'
        value: string | Shop
      } | null)
    | ({
        relationTo: 'courses'
        value: string | Course
      } | null)
    | ({
        relationTo: 'course-modules'
        value: string | CourseModule
      } | null)
    | ({
        relationTo: 'course-progress'
        value: string | CourseProgress
      } | null)
    | ({
        relationTo: 'enrollments'
        value: string | Enrollment
      } | null)
    | ({
        relationTo: 'lesson-progress'
        value: string | LessonProgress
      } | null)
    | ({
        relationTo: 'course-reviews'
        value: string | CourseReview
      } | null)
    | ({
        relationTo: 'certificates'
        value: string | Certificate
      } | null)
    | ({
        relationTo: 'certificate-templates'
        value: string | CertificateTemplate
      } | null)
    | ({
        relationTo: 'forms'
        value: string | Form
      } | null)
    | ({
        relationTo: 'form-submissions'
        value: string | FormSubmission
      } | null)
    | ({
        relationTo: 'search'
        value: string | Search
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: string | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string
  user: {
    relationTo: 'users'
    value: string | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T
  isActive?: T
  lastLogin?: T
  isVerified?: T
  memberCategory?: T
  officialMemberProfile?: T
  unofficialMemberProfile?: T
  otp?: T
  otpExpiry?: T
  otpAttempts?: T
  passwordResetToken?: T
  passwordResetExpiry?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
  authProvider?: T
  googlePicture?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  user?: T
  action?: T
  collectionName?: T
  documentId?: T
  documentTitle?: T
  changes?: T
  ipAddress?: T
  userAgent?: T
  status?: T
  details?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  memberId?: T
  username?: T
  user?: T
  firstName?: T
  lastName?: T
  fullName?: T
  email?: T
  avatar?: T
  bio?: T
  memberType?: T
  skills?:
    | T
    | {
        skill?: T
        level?: T
        id?: T
      }
  enrolledCourses?: T
  completedCourses?: T
  certificates?:
    | T
    | {
        course?: T
        issuedDate?: T
        certificateUrl?: T
        id?: T
      }
  totalPoints?: T
  level?: T
  isActive?: T
  committeeRoles?:
    | T
    | {
        committee?: T
        role?: T
        id?: T
      }
  directoryApprovalStatus?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees_select".
 */
export interface CommitteesSelect<T extends boolean = true> {
  name?: T
  slug?: T
  description?: T
  badgeColor?: T
  priority?: T
  isActive?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unofficial-members_select".
 */
export interface UnofficialMembersSelect<T extends boolean = true> {
  user?: T
  firstName?: T
  lastName?: T
  email?: T
  avatar?: T
  bio?: T
  institutionName?: T
  department?: T
  submissionDetails?: T
  status?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T
  alt?: T
  description?: T
  usage?: T
  imageKitUrl?: T
  imageKitFileId?: T
  imageKitSyncedAt?: T
  imageKitError?: T
  fileSize?: T
  duration?: T
  usageCount?: T
  lastUsed?: T
  uploadedBy?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        card?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        hero?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T
  slug?: T
  description?: T
  type?: T
  parent?: T
  thumbnail?: T
  color?: T
  status?: T
  order?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  excerpt?: T
  content?: T
  featuredImage?: T
  author?: T
  category?: T
  tags?:
    | T
    | {
        tag?: T
        id?: T
      }
  status?: T
  publishedAt?: T
  readingTime?: T
  featured?: T
  seoTitle?: T
  seoDescription?: T
  viewCount?: T
  likeCount?: T
  seo?:
    | T
    | {
        metaTitle?: T
        metaDescription?: T
        metaKeywords?: T
        canonicalUrl?: T
        noIndex?: T
        openGraph?:
          | T
          | {
              ogTitle?: T
              ogDescription?: T
              ogImage?: T
            }
        twitterCard?:
          | T
          | {
              twitterTitle?: T
              twitterDescription?: T
              twitterImage?: T
            }
      }
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  summary?: T
  content?: T
  coverImage?: T
  gallery?:
    | T
    | {
        image?: T
        caption?: T
        id?: T
      }
  achievementDate?: T
  venue?: T
  organizer?: T
  badge?: T
  status?: T
  featured?: T
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop_select".
 */
export interface ShopSelect<T extends boolean = true> {
  title?: T
  slug?: T
  shortDescription?: T
  description?: T
  featuredImage?: T
  gallery?:
    | T
    | {
        image?: T
        id?: T
      }
  productCategory?: T
  sku?: T
  memberType?: T
  pricing?:
    | T
    | {
        officialMemberPrice?: T
        unofficialMemberPrice?: T
        currency?: T
      }
  purchaseContact?:
    | T
    | {
        whatsappNumber?: T
        whatsappMessage?: T
      }
  stockStatus?: T
  sortOrder?: T
  status?: T
  isFeatured?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  shortDescription?: T
  description?: T
  thumbnail?: T
  previewVideo?: T
  category?: T
  tags?:
    | T
    | {
        tag?: T
        id?: T
      }
  level?: T
  language?: T
  instructor?: T
  coInstructors?: T
  memberType?: T
  pricing?:
    | T
    | {
        officialMemberPrice?: T
        unofficialMemberPrice?: T
        currency?: T
      }
  enrollmentContact?:
    | T
    | {
        whatsappNumber?: T
        whatsappMessage?: T
      }
  duration?:
    | T
    | {
        totalHours?: T
        totalWeeks?: T
      }
  requirements?:
    | T
    | {
        requirement?: T
        id?: T
      }
  learningOutcomes?:
    | T
    | {
        outcome?: T
        id?: T
      }
  modules?:
    | T
    | {
        title?: T
        description?: T
        order?: T
        lessons?:
          | T
          | {
              title?: T
              type?: T
              order?: T
              duration?: T
              isFreePreview?: T
              videoUrl?: T
              videoFile?: T
              documentFile?: T
              documentContent?: T
              description?: T
              id?: T
            }
        id?: T
      }
  enrollmentCount?: T
  averageRating?: T
  completionCount?: T
  status?: T
  publishedAt?: T
  isFeatured?: T
  certificateTemplate?:
    | T
    | {
        issueCertificate?: T
        certificateTitle?: T
        certificateDescription?: T
        signatoryName?: T
        signatoryTitle?: T
        signatorySignature?: T
        clubLogo?: T
      }
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-modules_select".
 */
export interface CourseModulesSelect<T extends boolean = true> {
  course?: T
  title?: T
  order?: T
  type?: T
  content?: T
  videoUrl?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress_select".
 */
export interface CourseProgressSelect<T extends boolean = true> {
  member?: T
  course?: T
  completedModules?: T
  percentComplete?: T
  startedAt?: T
  completedAt?: T
  lastActivityAt?: T
  totalTimeSpent?: T
  quizAttempts?: T
  averageQuizScore?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  student?: T
  course?: T
  status?: T
  memberType?: T
  payment?:
    | T
    | {
        amount?: T
        currency?: T
        method?: T
        transactionId?: T
        paidAt?: T
        notes?: T
      }
  progress?: T
  lessonProgress?:
    | T
    | {
        lessonId?: T
        moduleId?: T
        completed?: T
        completedAt?: T
        watchedSeconds?: T
        lastAccessedAt?: T
        id?: T
      }
  lastLessonAccessed?: T
  enrolledAt?: T
  completedAt?: T
  expiresAt?: T
  certificate?: T
  adminNotes?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-progress_select".
 */
export interface LessonProgressSelect<T extends boolean = true> {
  enrollment?: T
  student?: T
  course?: T
  moduleId?: T
  lessonId?: T
  lessonType?: T
  completed?: T
  completedAt?: T
  watchedSeconds?: T
  totalSeconds?: T
  lastAccessedAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-reviews_select".
 */
export interface CourseReviewsSelect<T extends boolean = true> {
  student?: T
  course?: T
  enrollment?: T
  rating?: T
  headline?: T
  body?: T
  status?: T
  adminNote?: T
  isVerifiedPurchase?: T
  helpfulCount?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  serialNumber?: T
  student?: T
  course?: T
  enrollment?: T
  studentSnapshot?:
    | T
    | {
        fullName?: T
        memberId?: T
        memberType?: T
        email?: T
      }
  courseSnapshot?:
    | T
    | {
        title?: T
        instructorName?: T
        durationHours?: T
      }
  certificateTitle?: T
  certificateBody?: T
  signatoryName?: T
  signatoryTitle?: T
  issuedAt?: T
  completionDate?: T
  isValid?: T
  revokedReason?: T
  verificationCount?: T
  lastVerifiedAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificate-templates_select".
 */
export interface CertificateTemplatesSelect<T extends boolean = true> {
  name?: T
  type?: T
  templateHtml?: T
  cssStyles?: T
  backgroundImage?: T
  signatureImage?: T
  logoImage?: T
  status?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              required?: T
              defaultValue?: T
              id?: T
              blockName?: T
            }
        country?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              required?: T
              id?: T
              blockName?: T
            }
        email?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              required?: T
              id?: T
              blockName?: T
            }
        message?:
          | T
          | {
              message?: T
              id?: T
              blockName?: T
            }
        number?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              defaultValue?: T
              required?: T
              id?: T
              blockName?: T
            }
        select?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              defaultValue?: T
              placeholder?: T
              options?:
                | T
                | {
                    label?: T
                    value?: T
                    id?: T
                  }
              required?: T
              id?: T
              blockName?: T
            }
        state?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              required?: T
              id?: T
              blockName?: T
            }
        text?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              defaultValue?: T
              required?: T
              id?: T
              blockName?: T
            }
        textarea?:
          | T
          | {
              name?: T
              label?: T
              width?: T
              defaultValue?: T
              required?: T
              id?: T
              blockName?: T
            }
      }
  submitButtonLabel?: T
  confirmationType?: T
  confirmationMessage?: T
  redirect?:
    | T
    | {
        url?: T
      }
  emails?:
    | T
    | {
        emailTo?: T
        cc?: T
        bcc?: T
        replyTo?: T
        emailFrom?: T
        subject?: T
        message?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T
  submissionData?:
    | T
    | {
        field?: T
        value?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T
  format?: T
  limit?: T
  page?: T
  sort?: T
  sortOrder?: T
  locale?: T
  drafts?: T
  selectionToUse?: T
  fields?: T
  collectionSlug?: T
  where?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T
  importMode?: T
  matchField?: T
  status?: T
  summary?:
    | T
    | {
        imported?: T
        updated?: T
        total?: T
        issues?: T
        issueDetails?: T
      }
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T
  priority?: T
  doc?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T
  taskStatus?: T
  completedAt?: T
  totalTried?: T
  hasError?: T
  error?: T
  log?:
    | T
    | {
        executedAt?: T
        completedAt?: T
        taskSlug?: T
        taskID?: T
        input?: T
        output?: T
        state?: T
        error?: T
        id?: T
      }
  taskSlug?: T
  queue?: T
  waitUntil?: T
  processing?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-settings".
 */
export interface HeaderSetting {
  id: string
  siteTitle: string
  /**
   * Header logo image
   */
  logo?: (string | null) | Media
  showSearch?: boolean | null
  menuItems?:
    | {
        label: string
        href: string
        /**
         * Optional dropdown menu items for this menu
         */
        children?:
          | {
              label: string
              href: string
              /**
               * Short description shown in dropdown (optional)
               */
              description?: string | null
              id?: string | null
            }[]
          | null
        id?: string | null
      }[]
    | null
  languages?:
    | {
        label: string
        code: string
        id?: string | null
      }[]
    | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings".
 */
export interface FooterSetting {
  id: string
  companyName: string
  /**
   * Brief company or brand description that appears in the footer.
   */
  description?: string | null
  /**
   * Optional logo shown in the footer.
   */
  footerLogo?: (string | null) | Media
  contactEmail?: string | null
  contactPhone?: string | null
  officeAddress?: string | null
  columns?:
    | {
        title: string
        links?:
          | {
              label: string
              href: string
              id?: string | null
            }[]
          | null
        id?: string | null
      }[]
    | null
  legalLinks?:
    | {
        label: string
        href: string
        id?: string | null
      }[]
    | null
  /**
   * Displayed at the bottom of the footer.
   */
  copyrightText?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-settings_select".
 */
export interface HeaderSettingsSelect<T extends boolean = true> {
  siteTitle?: T
  logo?: T
  showSearch?: T
  menuItems?:
    | T
    | {
        label?: T
        href?: T
        children?:
          | T
          | {
              label?: T
              href?: T
              description?: T
              id?: T
            }
        id?: T
      }
  languages?:
    | T
    | {
        label?: T
        code?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  companyName?: T
  description?: T
  footerLogo?: T
  contactEmail?: T
  contactPhone?: T
  officeAddress?: T
  columns?:
    | T
    | {
        title?: T
        links?:
          | T
          | {
              label?: T
              href?: T
              id?: T
            }
        id?: T
      }
  legalLinks?:
    | T
    | {
        label?: T
        href?: T
        id?: T
      }
  copyrightText?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string
    name: string
    batchSize?: number | null
    collectionSlug:
      | 'users'
      | 'activities'
      | 'members'
      | 'unofficial-members'
      | 'media'
      | 'categories'
      | 'posts'
      | 'achievements'
      | 'shop'
      | 'courses'
      | 'course-modules'
      | 'course-progress'
      | 'enrollments'
      | 'lesson-progress'
      | 'course-reviews'
      | 'certificates'
      | 'certificate-templates'
      | 'forms'
      | 'form-submissions'
      | 'exports'
      | 'imports'
    drafts?: ('yes' | 'no') | null
    exportCollection: string
    fields?: string[] | null
    format: 'csv' | 'json'
    limit?: number | null
    locale?: string | null
    maxLimit?: number | null
    page?: number | null
    sort?: string | null
    userCollection?: string | null
    userID?: string | null
    where?:
      | {
          [k: string]: unknown
        }
      | unknown[]
      | string
      | number
      | boolean
      | null
  }
  output?: unknown
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string
    importCollection: string
    userID?: string | null
    userCollection?: string | null
    batchSize?: number | null
    debug?: boolean | null
    defaultVersionStatus?: ('draft' | 'published') | null
    maxLimit?: number | null
  }
  output?: unknown
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
